"use client";
import { useState } from "react";
import { savedWorlds, type JoinRequest, type OnlineStatus } from "@/lib/ninja-online-client";
import { validCode, type GameMode, type RoomView } from "@/lib/ninja-online";

export default function NinjaOnlinePanel({ view, status, connected, start, offline }: { view: RoomView | null; status: OnlineStatus | null; connected: boolean; start: (request: JoinRequest) => void; offline: () => void }) {
  const [name, setName] = useState(""), [mode, setMode] = useState<GameMode>("survival"), [invite, setInvite] = useState(() => typeof window !== "undefined" ? /^#world=([a-f0-9]{24})$/.exec(location.hash)?.[1] ?? "" : ""), [notice, setNotice] = useState("");
  const code = validCode(invite.trim()) ? invite.trim() : /#world=([a-f0-9]{24})$/.exec(invite.trim())?.[1];
  async function copyInvite() { if (!view) return; try { const url = new URL(location.href); url.hash = `world=${view.code}`; await navigator.clipboard.writeText(url.toString()); setNotice("Invite copied. Anyone with this link can join, up to 8 players."); } catch { setNotice("Copy the world code below to invite your friends."); } }
  return <section className="mc-online-panel" aria-labelledby="online-heading"><h4 id="online-heading">Play with friends</h4><p>Private worlds · 8 players · shared building · saved on the server.</p>
    {view && <><div className="mc-room-heading"><strong>{view.mode === "creative" ? "Creative world" : "Survival world"}</strong><span role="status" aria-live="polite">{view.players.length} / 8 · {status === "online" ? "Connected" : status === "error" ? "Connection failed" : "Reconnecting…"}</span></div><div className="mc-player-slots" role="list" aria-label="Players in this world">{Array.from({ length: 8 }, (_, i) => { const player = view.players[i]; return <div key={i} className="mc-player-slot" role="listitem">{player ? <><img src="/art/psymariux-head.png" width={32} height={32} alt="" className="pixel-art" /><span>{player.name}{player.id === view.playerId ? " (you)" : ""}</span></> : <span>Empty</span>}</div>; })}</div><label className="mc-online-field">World code<input readOnly value={view.code} onFocus={e => e.currentTarget.select()} /></label><button className="dream-button" onClick={copyInvite}>Copy invite link</button><p className="mc-online-notice" role="status">{notice || "Your local world stays separate. Online menus stop your controls, not your friends' game."}</p></>}
    {!connected && <><label className="mc-online-field">Your name<input value={name} maxLength={20} onChange={e => setName(e.target.value)} autoComplete="nickname" placeholder="Player name" /></label>{!code && <><div className="journal-tabs" role="group" aria-label="New world mode"><button className="dream-button" aria-pressed={mode === "survival"} onClick={() => setMode("survival")}>Survival</button><button className="dream-button" aria-pressed={mode === "creative"} onClick={() => setMode("creative")}>Creative</button></div><p>{mode === "creative" ? "Unlimited building blocks. Place and recover them together." : "Gather materials, craft and complete missions together."}</p><button className="dream-button" disabled={!name.trim()} onClick={() => start({ type: "create", name: name.trim(), mode })}>Create a saved world</button><hr /></>}<label className="mc-online-field">Friend’s invite<input value={invite} onChange={e => setInvite(e.target.value)} maxLength={500} placeholder="Paste invite link or world code" /></label><button className="dream-button" disabled={!name.trim() || !code} onClick={() => { if (code) start({ type: "join", name: name.trim(), code }); }}>Join world</button>{code && <button className="dream-button" onClick={() => setInvite("")}>Create a new world instead</button>}<h4>Your saved worlds</h4><div className="mc-saved-worlds">{savedWorlds().map(world => <button key={world.code} className="dream-button" onClick={() => start({ type: "resume", code: world.code, token: world.token })}><span>{world.name} · {world.mode}</span><small>{world.code}</small></button>)}{!savedWorlds().length && <p>No online worlds saved on this browser yet.</p>}</div></>}
    {connected && <button className="dream-button" onClick={offline}>Disconnect · return to local world</button>}
    <p className="journal-note">Online requires Redis linked to the Vercel project. If it is unavailable, you can still play and save offline.</p>
  </section>;
}
